# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ea54394003db764bf693c2c7572df32ad21ab90334bc500115182b646c8884a537625d59a3b1f6a0cef024f63b24b87462c17341e4cbacc6cf38db90ca47801

test:
  secret_key_base: cd5e81a53d587153fbf6fd1b9f39f68f01f6df1028b6bb1c848c725eac59cc20743b11421298b6dcf2ae3ae180141305769bd120d45e2c5beba73a367fba2d73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>